on:
  push:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        env:
          GH_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TRIGGER_TOKEN }}
          script: |
            try {
              const result = await github.rest.actions.createWorkflowDispatch({
                owner: 'zzak',
                repo: 'workflow-test',
                workflow_id: 'accept.yml',
                ref: 'main',
                inputs: {
                  ref: '${{ github.ref }}',
                  ref_name: '${{ github.ref_name }}',
                  ref_type: '${{ github.ref_type }}'
                },
              })
              console.log(result);
            } catch(error) {
              console.error(error);
              core.setFailed(error);
            }
