on:
  push:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run accept.yml \
            -f ref=${{ github.ref }} \
            -f ref_name=${{ github.ref_name }} \
            -f ref_type=${{ github.ref_type }} \
            -R zzak/workflow-test
